export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const SAVE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
export const UPDATE_COURSE_SECCESS = "UPDATE_COURSE_SECCESS";
export const API_CALL_WAIT = "API_CALL_WAIT";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
